defaults: &defaults
  juggernaut_address: '192.168.2.3'
  price_address: '188.64.170.156:85'
  request_emex: false
  #emex_income_rate: 1.0
  #avtorif_income_rate: 1.0
  #retail_rate: 1.0
  emex_income_rate: 1.07
  avtorif_income_rate: 1.13
  retail_rate: 1.10

development:
  <<: *defaults

production:
  <<: *defaults
