defaults: &defaults
  price_request_cache: '10'
  juggernaut_address: '5.214.159.2'
  redis_address: '5.214.159.2'
  redis_port: 6379
  price_address: '188.64.170.156:85'
  #price_address: 'kaprika.ru:81'
  request_emex: true
  #emex_income_rate: 1.0
  #avtorif_income_rate: 1.0
  #retail_rate: 1.0
  emex_income_rate: 1.07
  avtorif_income_rate: 1.13
  retail_rate: 1.10

development:
  <<: *defaults

production:
  <<: *defaults
