defaults: &defaults
  #emex_income_rate: 1.0
  #avtorif_income_rate: 1.0
  #retail_rate: 1.0
  emex_income_rate: 1.07
  avtorif_income_rate: 1.05
  retail_rate: 1.10

development:
  <<: *defaults

production:
  <<: *defaults
