defaults: &defaults
  price_request_cache: '10'
  redis_address: 'localhost'
  redis_port: 6379
  juggernaut_address: 'www.yaponama.ru'
  price_address: '188.64.170.156:85'
  request_emex: true
  emex_income_rate: 1.07
  avtorif_income_rate: 1.10
  retail_rate: 1.17

development:
  <<: *defaults

production:
  <<: *defaults
