defaults: &defaults
  price_request_cache: '10'
  redis_address: 'localhost'
  #redis_address: '5.214.159.2'
  redis_port: 6379
  juggernaut_address: 'www.yaponama.ru'
  #juggernaut_address: 'kaprika.ru'
  #juggernaut_address: '5.214.159.2'
  price_address: '188.64.170.156:85'
  #price_address: 'kaprika.ru:81'
  request_emex: true
  #request_emex: false
  emex_income_rate: 1.07
  avtorif_income_rate: 1.10
  retail_rate: 1.17
  emex_income_rate: 1.07
  avtorif_income_rate: 1.10
  retail_rate: 1.17

development:
  <<: *defaults

production:
  <<: *defaults
