defaults: &defaults
  juggernaut_address: '192.168.2.7'
  #emex_income_rate: 1.0
  #avtorif_income_rate: 1.0
  #retail_rate: 1.0
  emex_income_rate: 1.07
  avtorif_income_rate: 1.13
  retail_rate: 1.10

development:
  <<: *defaults

production:
  <<: *defaults
